// Package earnwallet provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package earnwallet

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// AllocateSeedReq defines model for AllocateSeedReq.
type AllocateSeedReq struct {
	// ExternalRef Opaque idempotency key defined by the caller; infra does not interpret it
	ExternalRef string `json:"external_ref"`
}

// AllocateSeedRes defines model for AllocateSeedRes.
type AllocateSeedRes struct {
	// ExternalRef Echoed back so a retried request can be matched to its response
	ExternalRef string `json:"external_ref"`

	// Seed Global seed in [1, 2^32-1], shared across chains
	Seed int64 `json:"seed"`
}

// CreateWithdrawalReq defines model for CreateWithdrawalReq.
type CreateWithdrawalReq struct {
	// Amount Decimal string; more precision than the token has is refused, not rounded
	Amount string `json:"amount"`

	// Chain Chain name as configured, lower case
	Chain string `json:"chain"`

	// ExternalId Caller's order id; also the idempotency key
	ExternalId string `json:"external_id"`

	// ToAddress Destination address
	ToAddress string `json:"to_address"`

	// TokenId Token contract address; must be configured for withdrawal
	TokenId string `json:"token_id"`
}

// CreateWithdrawalRes defines model for CreateWithdrawalRes.
type CreateWithdrawalRes struct {
	ExternalId string `json:"external_id"`
	Status     string `json:"status"`
}

// Error defines model for Error.
type Error struct {
	// Code 0 on success; any other value is a business failure.
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetAddressReq defines model for GetAddressReq.
type GetAddressReq struct {
	// Chain Chain name as configured, lower case, e.g. bsc
	Chain string `json:"chain"`

	// Factory Factory address; defaults to the chain's current factory
	Factory *string `json:"factory,omitempty"`

	// Seed Global seed in [1, 2^32-1]
	Seed int64 `json:"seed"`
}

// GetAddressRes defines model for GetAddressRes.
type GetAddressRes struct {
	Address string `json:"address"`
	Chain   string `json:"chain"`
	Factory string `json:"factory"`
	Seed    int64  `json:"seed"`
}

// GetWithdrawalReq defines model for GetWithdrawalReq.
type GetWithdrawalReq struct {
	ExternalId string `json:"external_id"`
}

// GetWithdrawalRes defines model for GetWithdrawalRes.
type GetWithdrawalRes struct {
	Amount       string     `json:"amount"`
	Chain        string     `json:"chain"`
	ConfirmedAt  *time.Time `json:"confirmed_at"`
	CreatedAt    time.Time  `json:"created_at"`
	ExternalId   string     `json:"external_id"`
	FailedReason string     `json:"failed_reason"`
	HeldReason   string     `json:"held_reason"`
	Status       string     `json:"status"`
	ToAddress    string     `json:"to_address"`
	TokenId      string     `json:"token_id"`
	TxHash       string     `json:"tx_hash"`
}

// ResolveAddressReq defines model for ResolveAddressReq.
type ResolveAddressReq struct {
	Address string `json:"address"`
	Chain   string `json:"chain"`
}

// ResolveAddressRes defines model for ResolveAddressRes.
type ResolveAddressRes struct {
	Address string `json:"address"`
	Chain   string `json:"chain"`
	Factory string `json:"factory"`
	Seed    int64  `json:"seed"`
}

// GetAddressParams defines parameters for GetAddress.
type GetAddressParams struct {
	// Chain Chain name as configured, lower case, e.g. bsc
	Chain string `form:"chain" json:"chain"`

	// Factory Factory address; defaults to the chain's current factory
	Factory *string `form:"factory,omitempty" json:"factory,omitempty"`

	// Seed Global seed in [1, 2^32-1]
	Seed int64 `form:"seed" json:"seed"`
}

// ResolveAddressParams defines parameters for ResolveAddress.
type ResolveAddressParams struct {
	Chain   string `form:"chain" json:"chain"`
	Address string `form:"address" json:"address"`
}

// AllocateSeedJSONRequestBody defines body for AllocateSeed for application/json ContentType.
type AllocateSeedJSONRequestBody = AllocateSeedReq

// CreateWithdrawalJSONRequestBody defines body for CreateWithdrawal for application/json ContentType.
type CreateWithdrawalJSONRequestBody = CreateWithdrawalReq

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAddress request
	GetAddress(ctx context.Context, params *GetAddressParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResolveAddress request
	ResolveAddress(ctx context.Context, params *ResolveAddressParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AllocateSeedWithBody request with any body
	AllocateSeedWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AllocateSeed(ctx context.Context, body AllocateSeedJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateWithdrawalWithBody request with any body
	CreateWithdrawalWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateWithdrawal(ctx context.Context, body CreateWithdrawalJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWithdrawal request
	GetWithdrawal(ctx context.Context, externalId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAddress(ctx context.Context, params *GetAddressParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAddressRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResolveAddress(ctx context.Context, params *ResolveAddressParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResolveAddressRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AllocateSeedWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAllocateSeedRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AllocateSeed(ctx context.Context, body AllocateSeedJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAllocateSeedRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateWithdrawalWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateWithdrawalRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateWithdrawal(ctx context.Context, body CreateWithdrawalJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateWithdrawalRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWithdrawal(ctx context.Context, externalId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWithdrawalRequest(c.Server, externalId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAddressRequest generates requests for GetAddress
func NewGetAddressRequest(server string, params *GetAddressParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/addresses")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "chain", runtime.ParamLocationQuery, params.Chain); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Factory != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "factory", runtime.ParamLocationQuery, *params.Factory); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "seed", runtime.ParamLocationQuery, params.Seed); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewResolveAddressRequest generates requests for ResolveAddress
func NewResolveAddressRequest(server string, params *ResolveAddressParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/addresses/resolve")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "chain", runtime.ParamLocationQuery, params.Chain); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "address", runtime.ParamLocationQuery, params.Address); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAllocateSeedRequest calls the generic AllocateSeed builder with application/json body
func NewAllocateSeedRequest(server string, body AllocateSeedJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAllocateSeedRequestWithBody(server, "application/json", bodyReader)
}

// NewAllocateSeedRequestWithBody generates requests for AllocateSeed with any type of body
func NewAllocateSeedRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/seeds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateWithdrawalRequest calls the generic CreateWithdrawal builder with application/json body
func NewCreateWithdrawalRequest(server string, body CreateWithdrawalJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateWithdrawalRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateWithdrawalRequestWithBody generates requests for CreateWithdrawal with any type of body
func NewCreateWithdrawalRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/withdrawals")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetWithdrawalRequest generates requests for GetWithdrawal
func NewGetWithdrawalRequest(server string, externalId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "external_id", runtime.ParamLocationPath, externalId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/withdrawals/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAddressWithResponse request
	GetAddressWithResponse(ctx context.Context, params *GetAddressParams, reqEditors ...RequestEditorFn) (*GetAddressResponse, error)

	// ResolveAddressWithResponse request
	ResolveAddressWithResponse(ctx context.Context, params *ResolveAddressParams, reqEditors ...RequestEditorFn) (*ResolveAddressResponse, error)

	// AllocateSeedWithBodyWithResponse request with any body
	AllocateSeedWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AllocateSeedResponse, error)

	AllocateSeedWithResponse(ctx context.Context, body AllocateSeedJSONRequestBody, reqEditors ...RequestEditorFn) (*AllocateSeedResponse, error)

	// CreateWithdrawalWithBodyWithResponse request with any body
	CreateWithdrawalWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateWithdrawalResponse, error)

	CreateWithdrawalWithResponse(ctx context.Context, body CreateWithdrawalJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateWithdrawalResponse, error)

	// GetWithdrawalWithResponse request
	GetWithdrawalWithResponse(ctx context.Context, externalId string, reqEditors ...RequestEditorFn) (*GetWithdrawalResponse, error)
}

type GetAddressResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Code 0 on success; any other value is a business failure.
		Code    int            `json:"code"`
		Data    *GetAddressRes `json:"data,omitempty"`
		Message string         `json:"message"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r GetAddressResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAddressResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ResolveAddressResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Code 0 on success; any other value is a business failure.
		Code    int                `json:"code"`
		Data    *ResolveAddressRes `json:"data,omitempty"`
		Message string             `json:"message"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r ResolveAddressResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResolveAddressResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AllocateSeedResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Code 0 on success; any other value is a business failure.
		Code    int              `json:"code"`
		Data    *AllocateSeedRes `json:"data,omitempty"`
		Message string           `json:"message"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r AllocateSeedResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AllocateSeedResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateWithdrawalResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Code 0 on success; any other value is a business failure.
		Code    int                  `json:"code"`
		Data    *CreateWithdrawalRes `json:"data,omitempty"`
		Message string               `json:"message"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r CreateWithdrawalResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateWithdrawalResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetWithdrawalResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Code 0 on success; any other value is a business failure.
		Code    int               `json:"code"`
		Data    *GetWithdrawalRes `json:"data,omitempty"`
		Message string            `json:"message"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r GetWithdrawalResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWithdrawalResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAddressWithResponse request returning *GetAddressResponse
func (c *ClientWithResponses) GetAddressWithResponse(ctx context.Context, params *GetAddressParams, reqEditors ...RequestEditorFn) (*GetAddressResponse, error) {
	rsp, err := c.GetAddress(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAddressResponse(rsp)
}

// ResolveAddressWithResponse request returning *ResolveAddressResponse
func (c *ClientWithResponses) ResolveAddressWithResponse(ctx context.Context, params *ResolveAddressParams, reqEditors ...RequestEditorFn) (*ResolveAddressResponse, error) {
	rsp, err := c.ResolveAddress(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResolveAddressResponse(rsp)
}

// AllocateSeedWithBodyWithResponse request with arbitrary body returning *AllocateSeedResponse
func (c *ClientWithResponses) AllocateSeedWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AllocateSeedResponse, error) {
	rsp, err := c.AllocateSeedWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAllocateSeedResponse(rsp)
}

func (c *ClientWithResponses) AllocateSeedWithResponse(ctx context.Context, body AllocateSeedJSONRequestBody, reqEditors ...RequestEditorFn) (*AllocateSeedResponse, error) {
	rsp, err := c.AllocateSeed(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAllocateSeedResponse(rsp)
}

// CreateWithdrawalWithBodyWithResponse request with arbitrary body returning *CreateWithdrawalResponse
func (c *ClientWithResponses) CreateWithdrawalWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateWithdrawalResponse, error) {
	rsp, err := c.CreateWithdrawalWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateWithdrawalResponse(rsp)
}

func (c *ClientWithResponses) CreateWithdrawalWithResponse(ctx context.Context, body CreateWithdrawalJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateWithdrawalResponse, error) {
	rsp, err := c.CreateWithdrawal(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateWithdrawalResponse(rsp)
}

// GetWithdrawalWithResponse request returning *GetWithdrawalResponse
func (c *ClientWithResponses) GetWithdrawalWithResponse(ctx context.Context, externalId string, reqEditors ...RequestEditorFn) (*GetWithdrawalResponse, error) {
	rsp, err := c.GetWithdrawal(ctx, externalId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWithdrawalResponse(rsp)
}

// ParseGetAddressResponse parses an HTTP response from a GetAddressWithResponse call
func ParseGetAddressResponse(rsp *http.Response) (*GetAddressResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAddressResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code 0 on success; any other value is a business failure.
			Code    int            `json:"code"`
			Data    *GetAddressRes `json:"data,omitempty"`
			Message string         `json:"message"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseResolveAddressResponse parses an HTTP response from a ResolveAddressWithResponse call
func ParseResolveAddressResponse(rsp *http.Response) (*ResolveAddressResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResolveAddressResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code 0 on success; any other value is a business failure.
			Code    int                `json:"code"`
			Data    *ResolveAddressRes `json:"data,omitempty"`
			Message string             `json:"message"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseAllocateSeedResponse parses an HTTP response from a AllocateSeedWithResponse call
func ParseAllocateSeedResponse(rsp *http.Response) (*AllocateSeedResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AllocateSeedResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code 0 on success; any other value is a business failure.
			Code    int              `json:"code"`
			Data    *AllocateSeedRes `json:"data,omitempty"`
			Message string           `json:"message"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateWithdrawalResponse parses an HTTP response from a CreateWithdrawalWithResponse call
func ParseCreateWithdrawalResponse(rsp *http.Response) (*CreateWithdrawalResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateWithdrawalResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code 0 on success; any other value is a business failure.
			Code    int                  `json:"code"`
			Data    *CreateWithdrawalRes `json:"data,omitempty"`
			Message string               `json:"message"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetWithdrawalResponse parses an HTTP response from a GetWithdrawalWithResponse call
func ParseGetWithdrawalResponse(rsp *http.Response) (*GetWithdrawalResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWithdrawalResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code 0 on success; any other value is a business failure.
			Code    int               `json:"code"`
			Data    *GetWithdrawalRes `json:"data,omitempty"`
			Message string            `json:"message"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
