// Package earnwallet provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package earnwallet

import (
	"context"
	"net/url"
	"time"
)

// AllocateSeedReq defines model for AllocateSeedReq.
type AllocateSeedReq struct {
	// ExternalRef Opaque idempotency key defined by the caller; infra does not interpret it
	ExternalRef string `json:"external_ref"`
}

// AllocateSeedRes defines model for AllocateSeedRes.
type AllocateSeedRes struct {
	// ExternalRef Echoed back so a retried request can be matched to its response
	ExternalRef string `json:"external_ref"`

	// Seed Global seed in [1, 2^32-1], shared across chains
	Seed int64 `json:"seed"`
}

// CreateWithdrawalReq defines model for CreateWithdrawalReq.
type CreateWithdrawalReq struct {
	// Amount Decimal string; more precision than the token has is refused, not rounded
	Amount string `json:"amount"`

	// Chain Chain name as configured, lower case
	Chain string `json:"chain"`

	// ExternalId Caller's order id; also the idempotency key
	ExternalId string `json:"external_id"`

	// ToAddress Destination address
	ToAddress string `json:"to_address"`

	// TokenId Token contract address; must be configured for withdrawal
	TokenId string `json:"token_id"`
}

// CreateWithdrawalRes defines model for CreateWithdrawalRes.
type CreateWithdrawalRes struct {
	ExternalId string `json:"external_id"`
	Status     string `json:"status"`
}

// Error defines model for Error.
type Error struct {
	// Code 0 on success; any other value is a business failure.
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetAddressReq defines model for GetAddressReq.
type GetAddressReq struct {
	// Chain Chain name as configured, lower case, e.g. bsc
	Chain string `json:"chain"`

	// Factory Factory address; defaults to the chain's current factory
	Factory *string `json:"factory,omitempty"`

	// Seed Global seed in [1, 2^32-1]
	Seed int64 `json:"seed"`
}

// GetAddressRes defines model for GetAddressRes.
type GetAddressRes struct {
	Address string `json:"address"`
	Chain   string `json:"chain"`
	Factory string `json:"factory"`
	Seed    int64  `json:"seed"`
}

// GetWithdrawalReq defines model for GetWithdrawalReq.
type GetWithdrawalReq struct {
	ExternalId string `json:"external_id"`
}

// GetWithdrawalRes defines model for GetWithdrawalRes.
type GetWithdrawalRes struct {
	Amount       string     `json:"amount"`
	Chain        string     `json:"chain"`
	ConfirmedAt  *time.Time `json:"confirmed_at"`
	CreatedAt    time.Time  `json:"created_at"`
	ExternalId   string     `json:"external_id"`
	FailedReason string     `json:"failed_reason"`
	HeldReason   string     `json:"held_reason"`
	Status       string     `json:"status"`
	ToAddress    string     `json:"to_address"`
	TokenId      string     `json:"token_id"`
	TxHash       string     `json:"tx_hash"`
}

// ResolveAddressReq defines model for ResolveAddressReq.
type ResolveAddressReq struct {
	Address string `json:"address"`
	Chain   string `json:"chain"`
}

// ResolveAddressRes defines model for ResolveAddressRes.
type ResolveAddressRes struct {
	Address string `json:"address"`
	Chain   string `json:"chain"`
	Factory string `json:"factory"`
	Seed    int64  `json:"seed"`
}

// GetAddressParams defines parameters for GetAddress.
type GetAddressParams struct {
	// Chain Chain name as configured, lower case, e.g. bsc
	Chain string `form:"chain" json:"chain"`

	// Factory Factory address; defaults to the chain's current factory
	Factory *string `form:"factory,omitempty" json:"factory,omitempty"`

	// Seed Global seed in [1, 2^32-1]
	Seed int64 `form:"seed" json:"seed"`
}

// ResolveAddressParams defines parameters for ResolveAddress.
type ResolveAddressParams struct {
	Chain   string `form:"chain" json:"chain"`
	Address string `form:"address" json:"address"`
}

// AllocateSeedJSONRequestBody defines body for AllocateSeed for application/json ContentType.
type AllocateSeedJSONRequestBody = AllocateSeedReq

// CreateWithdrawalJSONRequestBody defines body for CreateWithdrawal for application/json ContentType.
type CreateWithdrawalJSONRequestBody = CreateWithdrawalReq

// GetAddress forward lookup: chain plus factory plus seed to address.
//
// A non-zero code in the reply comes back as *APIError. Any other error is a
// transport failure, and the request may still have been served.
func (c *Client) GetAddress(ctx context.Context, params GetAddressParams) (*GetAddressRes, error) {
	path := "/v1/addresses"

	query := url.Values{}
	query.Set("chain", formatParam(params.Chain))
	if params.Factory != nil {
		query.Set("factory", formatParam(*params.Factory))
	}
	query.Set("seed", formatParam(params.Seed))

	return send[GetAddressRes](ctx, c, "GET", path, query, nil)
}

// ResolveAddress reverse lookup: chain plus address to seed.
//
// A non-zero code in the reply comes back as *APIError. Any other error is a
// transport failure, and the request may still have been served.
func (c *Client) ResolveAddress(ctx context.Context, params ResolveAddressParams) (*ResolveAddressRes, error) {
	path := "/v1/addresses/resolve"

	query := url.Values{}
	query.Set("chain", formatParam(params.Chain))
	query.Set("address", formatParam(params.Address))

	return send[ResolveAddressRes](ctx, c, "GET", path, query, nil)
}

// AllocateSeed allocate the seed bound to an external reference.
//
// A non-zero code in the reply comes back as *APIError. Any other error is a
// transport failure, and the request may still have been served.
func (c *Client) AllocateSeed(ctx context.Context, body AllocateSeedJSONRequestBody) (*AllocateSeedRes, error) {
	path := "/v1/seeds"

	return send[AllocateSeedRes](ctx, c, "POST", path, nil, body)
}

// CreateWithdrawal submit a payout order.
//
// A non-zero code in the reply comes back as *APIError. Any other error is a
// transport failure, and the request may still have been served.
func (c *Client) CreateWithdrawal(ctx context.Context, body CreateWithdrawalJSONRequestBody) (*CreateWithdrawalRes, error) {
	path := "/v1/withdrawals"

	return send[CreateWithdrawalRes](ctx, c, "POST", path, nil, body)
}

// GetWithdrawal read one payout order.
//
// A non-zero code in the reply comes back as *APIError. Any other error is a
// transport failure, and the request may still have been served.
func (c *Client) GetWithdrawal(ctx context.Context, externalId string) (*GetWithdrawalRes, error) {
	path := "/v1/withdrawals/{external_id}"
	path = replacePathParam(path, "external_id", externalId)

	return send[GetWithdrawalRes](ctx, c, "GET", path, nil, nil)
}

// The with-responses layer is intentionally not generated. It hands the
// {code,message,data} envelope back untouched, so every call site would unwrap
// it the same way; the methods above return the unwrapped data and an
// *APIError instead. See oapi-codegen.yaml.
//
// This file cannot be blank: text/template ignores a redefinition whose body is
// only comments or whitespace, so an empty override silently leaves the stock
// template in place.
