// Package earnwallet provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package earnwallet

import (
	"context"
	"time"
)

// Chain defines model for Chain.
type Chain struct {
	// Chain Name to pass as the chain parameter
	Chain *string `json:"chain,omitempty"`

	// ChainId EIP-155 id on evm and tvm; an id assigned by this service on svm, which has none. Read it alongside chain, never instead of it
	ChainId *int64 `json:"chain_id,omitempty"`

	// ChainType evm, svm or tvm; decides the address format
	ChainType *string `json:"chain_type,omitempty"`

	// Confirmations Depth a deposit must reach before its callback is sent
	Confirmations *int64   `json:"confirmations,omitempty"`
	Tokens        *[]Token `json:"tokens,omitempty"`
}

// CreateWithdrawalReq defines model for CreateWithdrawalReq.
type CreateWithdrawalReq struct {
	// Amount Decimal string; more precision than the token has is refused, not rounded
	Amount string `json:"amount"`

	// Chain Chain name as configured, lower case
	Chain string `json:"chain"`

	// ExternalId Caller's order id; also the idempotency key
	ExternalId string `json:"external_id"`

	// ToAddress Destination address
	ToAddress string `json:"to_address"`

	// TokenId Token contract address; must be configured for withdrawal
	TokenId string `json:"token_id"`
}

// CreateWithdrawalRes defines model for CreateWithdrawalRes.
type CreateWithdrawalRes struct {
	ExternalId string `json:"external_id"`
	Status     string `json:"status"`
}

// Deposit defines model for Deposit.
type Deposit struct {
	Address       *string    `json:"address,omitempty"`
	Amount        *string    `json:"amount,omitempty"`
	BlockHeight   *string    `json:"block_height,omitempty"`
	BlockTime     *string    `json:"block_time,omitempty"`
	Chain         *string    `json:"chain,omitempty"`
	ConfirmedAt   *time.Time `json:"confirmed_at,omitempty"`
	Currency      *string    `json:"currency,omitempty"`
	Decimals      *uint8     `json:"decimals,omitempty"`
	EventId       *string    `json:"event_id,omitempty"`
	FromAddress   *string    `json:"from_address,omitempty"`
	RawAmount     *string    `json:"raw_amount,omitempty"`
	TokenId       *string    `json:"token_id,omitempty"`
	TransferIndex *int64     `json:"transfer_index,omitempty"`
	TxHash        *string    `json:"tx_hash,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code 0 on success; any other value is a business failure.
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetWalletReq defines model for GetWalletReq.
type GetWalletReq struct {
	// Address Look up the seed that owns this address
	Address *string `json:"address,omitempty"`

	// Chain Chain name as configured, lower case, e.g. bsc
	Chain string `json:"chain"`

	// Seed Look up this seed; omit both seed and address to take a new one
	Seed *int64 `json:"seed,omitempty"`
}

// GetWalletRes defines model for GetWalletRes.
type GetWalletRes struct {
	Address string `json:"address"`
	Chain   string `json:"chain"`

	// Factory The factory this address was derived under
	Factory string `json:"factory"`

	// Seed Identifies this wallet on every chain, not just this one
	Seed int64 `json:"seed"`
}

// GetWithdrawalReq defines model for GetWithdrawalReq.
type GetWithdrawalReq struct {
	ExternalId string `json:"external_id"`
}

// GetWithdrawalRes defines model for GetWithdrawalRes.
type GetWithdrawalRes struct {
	Amount       string     `json:"amount"`
	Chain        string     `json:"chain"`
	ConfirmedAt  *time.Time `json:"confirmed_at"`
	CreatedAt    time.Time  `json:"created_at"`
	ExternalId   string     `json:"external_id"`
	FailedReason string     `json:"failed_reason"`
	HeldReason   string     `json:"held_reason"`
	Status       string     `json:"status"`
	ToAddress    string     `json:"to_address"`
	TokenId      string     `json:"token_id"`
	TxHash       string     `json:"tx_hash"`
}

// ListChainsReq defines model for ListChainsReq.
type ListChainsReq = map[string]interface{}

// ListChainsRes defines model for ListChainsRes.
type ListChainsRes struct {
	Chains []Chain `json:"chains"`
}

// ListDepositsReq defines model for ListDepositsReq.
type ListDepositsReq struct {
	// Chain Limit to one chain
	Chain *string `json:"chain,omitempty"`
	Page  *int64  `json:"page,omitempty"`

	// Since Credited at or after this instant, RFC3339
	Since *time.Time `json:"since"`
	Size  *int64     `json:"size,omitempty"`

	// Until Credited strictly before this instant, RFC3339
	Until *time.Time `json:"until"`
}

// ListDepositsRes defines model for ListDepositsRes.
type ListDepositsRes struct {
	Items []Deposit `json:"items"`
	Total int64     `json:"total"`
}

// ListWithdrawalsReq defines model for ListWithdrawalsReq.
type ListWithdrawalsReq struct {
	// Chain Limit to one chain
	Chain *string `json:"chain,omitempty"`
	Page  *int64  `json:"page,omitempty"`

	// Since Created at or after this instant, RFC3339
	Since *time.Time `json:"since"`
	Size  *int64     `json:"size,omitempty"`

	// Status accepted, held, planned, confirmed or failed
	Status *string `json:"status,omitempty"`

	// Until Created strictly before this instant, RFC3339
	Until *time.Time `json:"until"`
}

// ListWithdrawalsRes defines model for ListWithdrawalsRes.
type ListWithdrawalsRes struct {
	Items []Withdrawal `json:"items"`
	Total int64        `json:"total"`
}

// Token defines model for Token.
type Token struct {
	// Decimals amount == raw_amount / 10^decimals
	Decimals *uint8 `json:"decimals,omitempty"`

	// MaxDailyWithdrawal Rolling 24h ceiling; empty when unset
	MaxDailyWithdrawal *string `json:"max_daily_withdrawal,omitempty"`

	// MaxWithdrawal Per-order ceiling as a decimal string; empty when not withdrawable
	MaxWithdrawal *string `json:"max_withdrawal,omitempty"`
	Symbol        *string `json:"symbol,omitempty"`

	// TokenId Value to pass as token_id; the contract address, or empty for the native asset
	TokenId      *string `json:"token_id,omitempty"`
	Withdrawable *bool   `json:"withdrawable,omitempty"`
}

// Withdrawal defines model for Withdrawal.
type Withdrawal struct {
	Amount       *string    `json:"amount,omitempty"`
	Chain        *string    `json:"chain,omitempty"`
	ConfirmedAt  *time.Time `json:"confirmed_at"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Decimals     *uint8     `json:"decimals,omitempty"`
	ExternalId   *string    `json:"external_id,omitempty"`
	FailedReason *string    `json:"failed_reason,omitempty"`
	HeldReason   *string    `json:"held_reason,omitempty"`
	RawAmount    *string    `json:"raw_amount,omitempty"`
	Status       *string    `json:"status,omitempty"`
	ToAddress    *string    `json:"to_address,omitempty"`
	TokenId      *string    `json:"token_id,omitempty"`
	TxHash       *string    `json:"tx_hash,omitempty"`
}

// ListChainsJSONRequestBody defines body for ListChains for application/json ContentType.
type ListChainsJSONRequestBody = ListChainsReq

// ListDepositsJSONRequestBody defines body for ListDeposits for application/json ContentType.
type ListDepositsJSONRequestBody = ListDepositsReq

// GetWalletJSONRequestBody defines body for GetWallet for application/json ContentType.
type GetWalletJSONRequestBody = GetWalletReq

// GetWithdrawalJSONRequestBody defines body for GetWithdrawal for application/json ContentType.
type GetWithdrawalJSONRequestBody = GetWithdrawalReq

// ListWithdrawalsJSONRequestBody defines body for ListWithdrawals for application/json ContentType.
type ListWithdrawalsJSONRequestBody = ListWithdrawalsReq

// CreateWithdrawalJSONRequestBody defines body for CreateWithdrawal for application/json ContentType.
type CreateWithdrawalJSONRequestBody = CreateWithdrawalReq

// ListChains list the chains and tokens this deployment supports.
//
// A non-zero code in the reply comes back as *APIError. Any other error is a
// transport failure, and the request may still have been served.
func (c *Client) ListChains(ctx context.Context, body ListChainsJSONRequestBody) (*ListChainsRes, error) {
	path := "/v1/chain/list"

	return send[ListChainsRes](ctx, c, "POST", path, nil, body)
}

// ListDeposits list credited deposits for reconciliation.
//
// A non-zero code in the reply comes back as *APIError. Any other error is a
// transport failure, and the request may still have been served.
func (c *Client) ListDeposits(ctx context.Context, body ListDepositsJSONRequestBody) (*ListDepositsRes, error) {
	path := "/v1/deposit/list"

	return send[ListDepositsRes](ctx, c, "POST", path, nil, body)
}

// GetWallet get a deposit wallet by seed or address, or take a new one.
//
// A non-zero code in the reply comes back as *APIError. Any other error is a
// transport failure, and the request may still have been served.
func (c *Client) GetWallet(ctx context.Context, body GetWalletJSONRequestBody) (*GetWalletRes, error) {
	path := "/v1/wallet/get"

	return send[GetWalletRes](ctx, c, "POST", path, nil, body)
}

// GetWithdrawal read one payout order.
//
// A non-zero code in the reply comes back as *APIError. Any other error is a
// transport failure, and the request may still have been served.
func (c *Client) GetWithdrawal(ctx context.Context, body GetWithdrawalJSONRequestBody) (*GetWithdrawalRes, error) {
	path := "/v1/withdrawal/get"

	return send[GetWithdrawalRes](ctx, c, "POST", path, nil, body)
}

// ListWithdrawals list payout orders for reconciliation.
//
// A non-zero code in the reply comes back as *APIError. Any other error is a
// transport failure, and the request may still have been served.
func (c *Client) ListWithdrawals(ctx context.Context, body ListWithdrawalsJSONRequestBody) (*ListWithdrawalsRes, error) {
	path := "/v1/withdrawal/list"

	return send[ListWithdrawalsRes](ctx, c, "POST", path, nil, body)
}

// CreateWithdrawal submit a payout order.
//
// A non-zero code in the reply comes back as *APIError. Any other error is a
// transport failure, and the request may still have been served.
func (c *Client) CreateWithdrawal(ctx context.Context, body CreateWithdrawalJSONRequestBody) (*CreateWithdrawalRes, error) {
	path := "/v1/withdrawal/submit"

	return send[CreateWithdrawalRes](ctx, c, "POST", path, nil, body)
}

// The with-responses layer is intentionally not generated. It hands the
// {code,message,data} envelope back untouched, so every call site would unwrap
// it the same way; the methods above return the unwrapped data and an
// *APIError instead. See oapi-codegen.yaml.
//
// This file cannot be blank: text/template ignores a redefinition whose body is
// only comments or whitespace, so an empty override silently leaves the stock
// template in place.
