// Package earnwallet provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package earnwallet

import (
	"time"
)

// AllocateSeedReq defines model for AllocateSeedReq.
type AllocateSeedReq struct {
	// ExternalRef Opaque idempotency key defined by the caller; infra does not interpret it
	ExternalRef string `json:"external_ref"`
}

// AllocateSeedRes defines model for AllocateSeedRes.
type AllocateSeedRes struct {
	// ExternalRef Echoed back so a retried request can be matched to its response
	ExternalRef string `json:"external_ref"`

	// Seed Global seed in [1, 2^32-1], shared across chains
	Seed int64 `json:"seed"`
}

// CreateWithdrawalReq defines model for CreateWithdrawalReq.
type CreateWithdrawalReq struct {
	// Amount Decimal string; more precision than the token has is refused, not rounded
	Amount string `json:"amount"`

	// Chain Chain name as configured, lower case
	Chain string `json:"chain"`

	// ExternalId Caller's order id; also the idempotency key
	ExternalId string `json:"external_id"`

	// ToAddress Destination address
	ToAddress string `json:"to_address"`

	// TokenId Token contract address; must be configured for withdrawal
	TokenId string `json:"token_id"`
}

// CreateWithdrawalRes defines model for CreateWithdrawalRes.
type CreateWithdrawalRes struct {
	ExternalId string `json:"external_id"`
	Status     string `json:"status"`
}

// Error defines model for Error.
type Error struct {
	// Code 0 on success; any other value is a business failure.
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetAddressReq defines model for GetAddressReq.
type GetAddressReq struct {
	// Chain Chain name as configured, lower case, e.g. bsc
	Chain string `json:"chain"`

	// Factory Factory address; defaults to the chain's current factory
	Factory *string `json:"factory,omitempty"`

	// Seed Global seed in [1, 2^32-1]
	Seed int64 `json:"seed"`
}

// GetAddressRes defines model for GetAddressRes.
type GetAddressRes struct {
	Address string `json:"address"`
	Chain   string `json:"chain"`
	Factory string `json:"factory"`
	Seed    int64  `json:"seed"`
}

// GetWithdrawalReq defines model for GetWithdrawalReq.
type GetWithdrawalReq struct {
	ExternalId string `json:"external_id"`
}

// GetWithdrawalRes defines model for GetWithdrawalRes.
type GetWithdrawalRes struct {
	Amount       string     `json:"amount"`
	Chain        string     `json:"chain"`
	ConfirmedAt  *time.Time `json:"confirmed_at"`
	CreatedAt    time.Time  `json:"created_at"`
	ExternalId   string     `json:"external_id"`
	FailedReason string     `json:"failed_reason"`
	HeldReason   string     `json:"held_reason"`
	Status       string     `json:"status"`
	ToAddress    string     `json:"to_address"`
	TokenId      string     `json:"token_id"`
	TxHash       string     `json:"tx_hash"`
}

// ResolveAddressReq defines model for ResolveAddressReq.
type ResolveAddressReq struct {
	Address string `json:"address"`
	Chain   string `json:"chain"`
}

// ResolveAddressRes defines model for ResolveAddressRes.
type ResolveAddressRes struct {
	Address string `json:"address"`
	Chain   string `json:"chain"`
	Factory string `json:"factory"`
	Seed    int64  `json:"seed"`
}

// GetAddressParams defines parameters for GetAddress.
type GetAddressParams struct {
	// Chain Chain name as configured, lower case, e.g. bsc
	Chain string `form:"chain" json:"chain"`

	// Factory Factory address; defaults to the chain's current factory
	Factory *string `form:"factory,omitempty" json:"factory,omitempty"`

	// Seed Global seed in [1, 2^32-1]
	Seed int64 `form:"seed" json:"seed"`
}

// ResolveAddressParams defines parameters for ResolveAddress.
type ResolveAddressParams struct {
	Chain   string `form:"chain" json:"chain"`
	Address string `form:"address" json:"address"`
}

// AllocateSeedJSONRequestBody defines body for AllocateSeed for application/json ContentType.
type AllocateSeedJSONRequestBody = AllocateSeedReq

// CreateWithdrawalJSONRequestBody defines body for CreateWithdrawal for application/json ContentType.
type CreateWithdrawalJSONRequestBody = CreateWithdrawalReq
